default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: 12345
  host: 127.0.0.1
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "learn_rails"
